# This OAuth 2.0 access scope allows for full read/write access to the
# authenticated user's account.

ENDPOINT: https://www.googleapis.com/auth/youtube
YOUTUBE_API_SERVICE_NAME: youtube
YOUTUBE_API_VERSION: v3
USER: ramadantis
API_KEY: AIzaSyAD9cHpwwD_rQtsveLv7AJ5BeobmPkx21E

