# This OAuth 2.0 access scope allows for full read/write access to the
# authenticated user's account.
APP:
  ENDPOINT: https://todo.ly/
  TODO_API_ROOTPATH: api/


USERS:
  __MAURICIO_USER__: zelaya.mauricio@gmail.com
  __MAURICIO_PASS__: Control1234_

  __ALEJANDRO_USER__: alejandro.av84@gmail.com
  __ALEJANDRO_PASS__: bddPython

  __DENNIS_USER__: llgamboll@gmail.com
  __DENNIS_PASS__: P4ssw0rd

  USER_PABLO: PabloZ
  API__KEY_PABLO: AIzaSyBmBrstL4QTqAfEY7mTIrK17OrBVJuvxVQ
  USER_DANEIVA: Daneiva
  API__KEY_DANEIVA: AIzaSyAdbQ1hnwmA4wTTvHsS_HD1zrWceryrQeM
